import type { NextPage } from "next";
import Head from "next/head";
import styled from 'styled-components';
import _ from 'lodash';
import { BubblesPageWrapper } from "../components/BubblesPageWrapper";
import { StyledTitle } from "../components/StyledTitle";
import { ChipInput } from "../components/ChipInput";
import { JobCard } from "../components/jobCard";

const JobWrapper = styled.div`
  width: 100%;
  height: 100%;
  display: flex;
  flex-flow: wrap;
  justify-content: center;

  > div {
    margin: 2.8rem;
  }
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <StyledTitle>Znajdź swój projekt</StyledTitle>
        <ChipInput />
        <BubblesPageWrapper>
          <JobWrapper>
            {
              _.times(10, i =>
                <JobCard
                  key={i}
                  projectName="Piece wędzarnicze"
                  description="Portal do licytacji pieców wędzarniczych :>"
                  type="Strona internetowa"
                  technology="Dowolna"
                  revenue="Utajnione"
                  id="d322cdc0-4eb3-4065-8dc2-421014f5a906"
                />
              )
            }
          </JobWrapper>
        </BubblesPageWrapper>
      </main>

    </div>
  );
};

export default Home;
